################################
# MCP Gateway Operator
################################

FROM registry.redhat.io/ubi9/go-toolset:latest AS builder

ENV BINARY_NAME="mcp_controller"

WORKDIR /workspace

# Copy the Go Modules manifests
COPY mcp-gateway/go.mod go.mod
COPY mcp-gateway/go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY mcp-gateway/cmd/ cmd/
COPY mcp-gateway/internal/ internal/
COPY mcp-gateway/api/ api/
COPY mcp-gateway/LICENSE /licenses/LICENSE

ARG GITHUB_SHA
ENV GITHUB_SHA=${GITHUB_SHA:-unknown}

# Build MCP Gateway Operator
RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags "-X main.version=${GITHUB_SHA}" \
    -o ${BINARY_NAME} \
    cmd/main.go


FROM registry.redhat.io/ubi9/ubi-minimal:latest

LABEL version="0.7.1" \
      com.redhat.component="mcp-gateway-operator" \
      name="rhcl-tech-preview/mcp-gateway-operator-rhel9" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      vendor="Red Hat, Inc." \
      summary="MCP Gateway Kubernetes operator" \
      description="Kubernetes operator for discovering and managing MCP servers via MCPGatewayExtension, MCPServerRegistration, and MCPVirtualServer CRDs." \
      io.k8s.display-name="MCP Gateway Operator" \
      io.k8s.description="Kubernetes operator for MCP Gateway CRDs" \
      io.openshift.expose-services="" \
      io.openshift.tags="mcp, controller, kubernetes, operator" \
      url="redhat.com" \
      distribution-scope="public" \
      release="0.7.0" \
      vendor="Red Hat, Inc."

ENV OPERATOR_BINARY_NAME="mcp_controller" \
    USER_UID=1001 \
    USER_NAME=mcp-gateway-operator

USER root

# install operator binary
COPY --from=builder /workspace/${OPERATOR_BINARY_NAME} /
RUN chown ${USER_UID} /${OPERATOR_BINARY_NAME}

COPY --from=builder /licenses/LICENSE ./licenses/LICENSE

ENTRYPOINT ["/mcp_controller"]

USER ${USER_UID}
