FROM scratch

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=mcp-gateway
LABEL operators.operatorframework.io.bundle.channels.v1=preview
LABEL operators.operatorframework.io.bundle.channel.default.v1=preview

LABEL com.redhat.component="mcp-gateway-operator-bundle-container" \
      name="rhcl-1/mcp-gateway-operator-bundle" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      vendor="Red Hat, Inc." \
      summary="MCP Gateway OLM bundle (stage)" \
      description="OLM bundle image containing ClusterServiceVersion and CRDs for MCP Gateway operator (stage)" \
      io.k8s.display-name="MCP Gateway Bundle (stage)" \
      io.openshift.tags="mcp, operator, bundle"

COPY bundle-stage/manifests /manifests/
COPY bundle-stage/metadata /metadata/
