################################
# MCP Gateway
################################

FROM registry.redhat.io/ubi9/go-toolset:latest AS builder

ENV BINARY_NAME="mcp_gateway"

WORKDIR /workspace

# Copy the Go Modules manifests
COPY mcp-gateway/go.mod go.mod
COPY mcp-gateway/go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY mcp-gateway/cmd/ cmd/
COPY mcp-gateway/internal/ internal/
COPY mcp-gateway/api/ api/
COPY mcp-gateway/LICENSE /licenses/LICENSE

ARG GITHUB_SHA
ENV GITHUB_SHA=${GITHUB_SHA:-unknown}

# Build MCP Gateway
RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags "-X main.version=${GITHUB_SHA}" \
    -o ${BINARY_NAME} \
    cmd/mcp-broker-router/main.go


FROM registry.redhat.io/ubi9/ubi-minimal:latest

LABEL version="0.7.0-rc3" \
      com.redhat.component="mcp-gateway" \
      name="rhcl-tech-preview/mcp-gateway-rhel9" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      vendor="Red Hat, Inc." \
      summary="MCP Gateway broker and router" \
      description="Envoy-based gateway for Model Context Protocol (MCP) servers. Routes MCP requests through Envoy and federates tools from multiple upstream MCP servers." \
      io.k8s.display-name="MCP Gateway" \
      io.k8s.description="Envoy-based gateway for Model Context Protocol (MCP) servers" \
      io.openshift.expose-services="" \
      io.openshift.tags="mcp, gateway, envoy, ai" \
      url="redhat.com" \
      distribution-scope="public" \
      release="0.7.0" \
      vendor="Red Hat, Inc."

ENV OPERATOR_BINARY_NAME="mcp_gateway" \
    USER_UID=1001 \
    USER_NAME=mcp-gateway

USER root

# install operator binary
COPY --from=builder /workspace/${OPERATOR_BINARY_NAME} /
RUN chown ${USER_UID} /${OPERATOR_BINARY_NAME}

COPY --from=builder /licenses/LICENSE ./licenses/LICENSE

ENTRYPOINT ["/mcp_gateway", "--mcp-gateway-config=/config/config.yaml"]

USER ${USER_UID}
