FROM scratch

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=mcp-gateway
LABEL operators.operatorframework.io.bundle.channels.v1=preview
LABEL operators.operatorframework.io.bundle.channel.default.v1=preview

LABEL version="0.7.0" \
      summary="MCP Gateway enables you to federate, secure, and route Model Context Protocol (MCP) traffic through an Envoy-based gateway." \
      name="rhcl-tech-preview/rhcl-operator-bundle" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      description="MCP Gateway enables you to federate, secure, and route Model Context Protocol (MCP) traffic through an Envoy-based gateway." \
      io.k8s.display-name="MCP Gateway Operator Bundle" \
      io.k8s.description="MCP Gateway Operator Bundle" \
      io.openshift.expose-services="" \
      io.openshift.tags="api, mcp, gateway" \
      url="redhat.com" \
      distribution-scope="public" \
      release="1.4.0" \
      com.redhat.component="MCP Gateway Operator Bundle" \
      vendor="Red Hat, Inc."

COPY bundle-stage/manifests /manifests/
COPY bundle-stage/metadata /metadata/
