FROM scratch

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=mcp-gateway
LABEL operators.operatorframework.io.bundle.channels.v1=preview
LABEL operators.operatorframework.io.bundle.channel.default.v1=preview

LABEL com.redhat.component="mcp-controller-bundle-container" \
      name="rhcl-1/mcp-controller-bundle" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      vendor="Red Hat, Inc." \
      summary="MCP Gateway OLM bundle (dev)" \
      description="OLM bundle image containing ClusterServiceVersion and CRDs for MCP Gateway operator (dev)" \
      io.k8s.display-name="MCP Gateway Bundle (dev)" \
      io.openshift.tags="mcp, operator, bundle"

COPY bundle-dev/manifests /manifests/
COPY bundle-dev/metadata /metadata/
